#!/usr/bin/env sh
while getopts "b" OPTION
do
  case $OPTION in
    b)
      BUILD="build"
      ;;
  esac
done

DATABASE_URL=$(heroku config --json | jq -r .DATABASE_URL)

if [ -n "$BUILD" ]; then
  docker build -t local/postgres-cli --build-arg "DATABASE_URL=$DATABASE_URL" .
fi
docker run --rm -it local/postgres-cli
