#!/usr/bin/env node

import sequelize from '../server/lib/db';

import Game from '../server/models/game';
import Player from '../server/models/player';
import Card from '../server/models/card';

sequelize.sync();
